version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "Installing dependencies for Lambda..."
      - echo "Zipping Lambda function..."
      - cd lambda && zip -r deployment_package.zip ./*
      - pwd
      - ls
  post_build:
    commands:
      - pwd
      - echo "Deploying Lambda function..."
      - aws lambda update-function-code --function-name kbom-api --zip-file fileb://deployment_package.zip
artifacts:
  files:
    - lambda/deployment_package.zip