version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - echo "Checking if S3 bucket exists..."
      - |
        if aws s3api head-bucket --bucket kbom-reports-bucket-1243 2>/dev/null; then
          echo "Bucket already exists. Skipping creation."
        else
          echo "Bucket does not exist. Creating..."
          aws s3api create-bucket --bucket kbom-reports-bucket-1243 --region $AWS_REGION
        fi